### PR TITLE
Updates for julia-0.7

### PR DESCRIPTION
**Pull request by ederag**
WIP. Updates for julia-0.7 (using Plots still has errors)

currently stuck on
```
ERROR: LoadError: LoadError: LoadError: Must call userplot on a type/immutable expression.  Got: mutable struct ShowTheme
    #= /home/ederag/.julia/v0.7/RecipesBase/src/RecipesBase.jl:374 =#
    args
end
```

It seem related to the [deprecation of `type`](https://github.com/JuliaLang/julia/blob/master/NEWS.md#deprecated-or-removed)

Replacing `@userplot` with
```
@userplot mutable struct ShowTheme
    args
end
```
now `_userplot` in `RecipesBase.jl` fails with
`Must call userplot on a type/immutable expression.  Got: mutable struct ShowTheme`
Tried to replace
`if expr.head != :type` with
`if ! isstructtype(expr.head)`
but then
`LoadError: MethodError: no method matching isstructtype(::Symbol)`

Updating `_userplot` is too much for a julia newbie.
Giving up.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Yes, this is definitely very advanced stuff for a julia newbie. You're welcome to make a smaller functional PR to the 0.7 branch on the JuliaPlots fork fork of Plots (this is my personal fork).

**Comment by ederag** [comment]
A PR to your fork was intentional, since you already started working on a julia v0.7 branch, 
and it was not possible to test it before the advanced stuff is solved. 
You could just use that as a starting point, to save some time.
But maybe you mean that femtocleaner will be used and this PR is not necessary any longer ?

**Comment by mkborregaard** [comment]
Femtocleaner will be used, yes. 
There's also a 0.7 branch on the JuliaPlots repo. But thanks for the effort, much appreciated.

**Comment by ederag** [comment]
Understood.

**Pull request closed without merging**
